### ISSUE TITLE
Setup Dependabot

### ISSUE THREAD

**Issue by mziyut** [increments/qiita-markdown#121]
## What

- Set up "Dependabot" for continuous library updates.

```yml
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
```
